version: '2'

services: 
#  keepalive:
#    image: osixia/keepalived:1.4.5
#    container_name: keepalived
#    environment:
#      - KEEPALIVED_INTERFACE="enp0s3"
#      - KEEPALIVED_VIRTUAL_IPS="192.168.1.10"
#      - KEEPALIVED_PRIORITY =150
#      - KEEPALIVED_UNICAST_PEERS="192.168.1.42"
#      - KEEPALIVED_COMMAND_LINE_ARGUMENTS=""
#    network_mode: host

  nginx:
    image: nginx:1.14.0
    build:
        context: dockerfile/nginx
    container_name: nginx
    volumes:
        - ${PWD}/conf/nginx/:/etc/nginx/
        - ${PWD}/swi:/opt
    depends_on:
      - mars
    network_mode: host

  elasticsearch:
    build:
        context: dockerfile/elasticsearch 
    container_name: elasticsearch
    privileged: true
    network_mode: host
    #volumes:
      #- ${PWD}/conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #- ${PWD}/conf/elasticsearch/data:/usr/share/elasticsearch/data:rw
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      network.bind_host: "127.0.0.1"
      network.publish_host: "192.168.200.65"
      cluster.name: "marscluster"
      node.name: "es1"


  logstash:
    build: 
      context: dockerfile/logstash      
    container_name: logstash
    privileged: true
    network_mode: host
    volumes:
      - ${PWD}/conf/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ${PWD}/conf/logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    depends_on:
      - elasticsearch

  mars:
    image: mars:1.0.0.9
    container_name: mars
    network_mode: host
    privileged: true
    environment:
      ONOS_IP: HOST_IP_TO_ONOS_IP
    volumes:
      - ${PWD}/conf/mars/modules:/etc/collectd/modules
      - ${PWD}/conf/mars/mars_collectd.conf:/etc/collectd/collectd.conf
    depends_on:
      - elasticsearch

